### ISSUE TITLE
ansible galaxy hangs "Loading your role repositories from GitHub..."

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [ansible/galaxy-issues#163]
situation:

1) signed up for new account via github

2) tried to import roles https://galaxy.ansible.com/roleadd#/

3) ansible galaxy hangs on "Loading your role repositories from GitHub..."

how can I reset/fix this?

**Comment by Andrei-Pozolotin** [comment]
command line token login works fine:
http://docs.ansible.com/ansible/galaxy.html#authenticate-with-galaxy

but command line import
http://docs.ansible.com/ansible/galaxy.html#import-a-role

also fails: `ansible-galaxy -vvv import github_user github_repo`

```
Using /etc/ansible/ansible.cfg as config file
Opened /root/.ansible_galaxy
Validate TLS certificates: True
None/imports/
ERROR! Unexpected Exception: unknown url type: None/imports/
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 153, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 100, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 596, in execute_import
    task = self.api.create_import_task(github_user, github_repo, reference=self.options.reference)
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/api.py", line 143, in create_import_task
    data = self.__call_galaxy(url, args=args)
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/api.py", line 95, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/imports/
```

**Comment by Andrei-Pozolotin** [comment]
here is the repo in question:
https://github.com/random-archer/ansible-role-thinkpad

**Comment by chouseknecht** [comment]
It's not hanging anymore. There was an issue a couple weeks back where imports were failing, and that was fixed. 

Forking ansible-role-thinkpad today and importing it yields the following:

![archer_role](https://cloud.githubusercontent.com/assets/1282865/16745145/8167abe6-4782-11e6-84b8-571d010b7480.png)

Looks like you need to add a README file.

**Comment by KAMI911** [comment]
I have same issue:
`ansible-galaxy import -vvv kami911 ansible-role-java-oracle-jdk8
Using /etc/ansible/ansible.cfg as config file
Opened /home/kami/.ansible_galaxy
None/imports/
ERROR! Unexpected Exception: unknown url type: None/imports/
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 577, in execute_import
    task = self.api.create_import_task(github_user, github_repo, reference=self.options.reference)
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/api.py", line 140, in create_import_task
    data = self.__call_galaxy(url, args=args)
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/api.py", line 92, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/imports/
`
