### ISSUE TITLE
CLI login fails

### ISSUE THREAD

**Issue by kuza55** [ansible/galaxy-issues#167]
When I try to login on the command line I get this:

```
$ ansible-galaxy -vvv login
Using /etc/ansible/ansible.cfg as config file
Opened /home/alex/.ansible_galaxy
Validate TLS certificates: True


We need your Github login to identify you.
This information will not be sent to Galaxy, only to api.github.com.
The password will not be displayed.

Use --github-token if you do not want to enter your password.

Github Username: kuza55
Password for kuza55:
ERROR! Unexpected Exception: HTTP Error 400: BAD REQUEST
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 153, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 100, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 560, in execute_login
    galaxy_response = self.api.authenticate(github_token)
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/api.py", line 129, in authenticate
    resp = open_url(url, data=args, validate_certs=self._validate_certs, method="POST")
  File "/usr/lib/python2.7/dist-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: BAD REQUEST
```

I get similar errors when I pass in a token on the command line.

FWIW, I am running this via Ubuntu on Windows 10, though it seems unlikely to be causing these issues.

**Comment by chouseknecht** [comment]
@kuza55 what version of Ansible?

Not able to reproduce this using the latest from the Ansible devel branch.

```
$ ansible --version
ansible 2.2.0 (devel 584ffe0c64) last updated 2016/07/05 11:43:43 (GMT -400)
  lib/ansible/modules/core: (fix_4091 f5e8204dbc) last updated 2016/07/05 11:47:18 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 00b8b96906) last updated 2016/07/05 11:43:54 (GMT -400)
  config file = /Users/chouseknecht/projects/ansible.cfg
  configured module search path = Default w/o overrides
```

Here's me logging in:

```
$ ansible-galaxy login

We need your Github login to identify you.
This information will not be sent to Galaxy, only to api.github.com.
The password will not be displayed.

Use --github-token if you do not want to enter your password.

Github Username: chouseknecht
Password for chouseknecht:
Succesfully logged into Galaxy as chouseknecht
```

**Comment by kuza55** [comment]
@chouseknecht 

```
$ ansible-galaxy login --version
ansible-galaxy 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Can I install the devel branch in it's own directory in some way to see if that works for me?

**Comment by s-hertel** [comment]
Are you able to login at https://galaxy.ansible.com? If your github account hasn't been linked to galaxy yet it will raise that error.

**Comment by chouseknecht** [comment]
You can run from source as described here: http://docs.ansible.com/ansible/intro_installation.html#running-from-source

**Comment by kuza55** [comment]
@s-hertel Thank you! Once I signed up with my github account it worked, it wasn't mentioned anywhere as a requirement.

**Comment by s-hertel** [comment]
@kuza55 Happy it helped! I'll work on adding a feature to give a more helpful error for instances when the github account isn't linked to galaxy.

**Comment by Miyurz** [comment]
@s-hertel Thank you. As @kuza55 mentioned, it wasn't documented well and the error was misleading.
