### ISSUE TITLE
Unable to update role

### ISSUE THREAD

**Issue by felnne** [ansible/galaxy-issues#170]
Hi,

I have a role [bas-ansible-roles-collection.php5](https://galaxy.ansible.com/bas-ansible-roles-collection/php5/) which I need to re-import to pick up a new role version.

I don't see this role on the my imports page however. It shows up in the list of roles I can import, and shows as it hasn't been imported, but if I try to re-import it, it just hangs forever.

Clicking 'running' whilst the import runs takes me to [this](https://galaxy.ansible.com/imports#/?github_user=bas-ansible-roles-collection&github_repo=php5) page, but that role doesn't appear in the list of available roles.

From the role description page I can see no way to trigger a re-import.

Could someone take a look at what's going on? It seems like some association has broken between my account and the role.

Thanks.

**Comment by mat-green** [comment]
Hello,

I have the same problem for my [Rundeck Role](https://galaxy.ansible.com/neel/rundeck/). Any updates on this?

**Comment by s-hertel** [comment]
Hello, I was unable to recreate this issue. From the command line can you run `ansible-galaxy login -vvv` (or `ansible-galaxy login --github-token your_github_token -vvv`) and then `ansible-galaxy import your_github_username your_github_repo -vvv` and post the output of that, please?

**Comment by mat-green** [comment]
I am using the web interface to re-import but I will try the cli.
Thanks
M

**Comment by felnne** [comment]
@s-hertel,

I've tried that and get some errors (didn't realise there was a way of doing this through a CLI!)

```
$ ansible-galaxy login --github-token xxx
Succesfully logged into Galaxy as felnne

$ ansible-galaxy import bas-ansible-roles-collection php5 -vvv
Using /Users/felnne/.ansible.cfg as config file
Opened /Users/felnne/.ansible_galaxy
Validate TLS certificates: True
None/imports/
ERROR! Unexpected Exception: unknown url type: None/imports/
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 153, in run
    self.execute()
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/cli/__init__.py", line 100, in execute
    fn()
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 596, in execute_import
    task = self.api.create_import_task(github_user, github_repo, reference=self.options.reference)
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/galaxy/api.py", line 143, in create_import_task
    data = self.__call_galaxy(url, args=args)
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/galaxy/api.py", line 95, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/imports/
```

---

```
$ cat ~/.ansible.cfg
# config file for ansible -- http://ansible.com/

[ssh_connection]
control_path = %(directory)s/%%h-%%r
```

---

```
$ ansible --version
ansible 2.1.0.0
  config file = /Users/felnne/.ansible.cfg
  configured module search path = Default w/o overrides
```

---

Happy to try anything else to get this sorted, though i'm not a Python dev.

**Comment by s-hertel** [comment]
@mat-green I tried recreating the issue using the web interface and couldn't. Someone with access to the private webapp repo will need to look into this.

@felnne Someone with access to the private galaxy repo will need to look into this issue. The GalaxyCLI is a potential workaround until that happens (this commit: https://github.com/ansible/ansible/commit/7e834f41782a7fb57c9a7b1771e8448a6ae5ad34 will fix the error you had and will be in the next release). Sorry to not be able to get to the root of the issue!

**Comment by mat-green** [comment]
Thank you for the advice, it is working for me.

**Comment by chouseknecht** [comment]
@felnne, closing this for now. I am able to import a fork of you php role in the [QA site](https://galaxy-qa.ansible.com), and at the [main site](https://galaxy.ansible.com).

**Comment by felnne** [comment]
@chouseknecht - i'd forgotten about this issue to be honest, but trying to reimport my role worked so happy to close this.

Thanks.
