### ISSUE TITLE
Cannot import role via CLI: "unknown url type: None/imports/"

### ISSUE THREAD

**Issue by c-mart** [ansible/galaxy-issues#181]
Tried this:

```
$ ansible-galaxy login

We need your Github login to identify you.
This information will not be sent to Galaxy, only to api.github.com.
The password will not be displayed.

Use --github-token if you do not want to enter your password.

Github Username: c-mart
Password for c-mart: 
Succesfully logged into Galaxy as c-mart

$ ansible-galaxy import c-mart ansible-galaxy-test-cowsay -vvv
Using /etc/ansible/ansible.cfg as config file
Opened /home/cmart/.ansible_galaxy
None/imports/
ERROR! Unexpected Exception: unknown url type: None/imports/
the full traceback was:

Traceback (most recent call last):
  File "/home/cmart/.local/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 577, in execute_import
    task = self.api.create_import_task(github_user, github_repo, reference=self.options.reference)
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 140, in create_import_task
    data = self.__call_galaxy(url, args=args)
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 92, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/home/cmart/.local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None/imports/

```

Same result when I pass `--server https://galaxy-qa.ansible.com`.

```
$ ansible-galaxy --version
ansible-galaxy 2.1.1.0
```

**Comment by c-mart** [comment]
[This commit](https://github.com/ansible/ansible/commit/7e834f41782a7fb57c9a7b1771e8448a6ae5ad34) fixes it for me.
