### ISSUE TITLE
Can't delete roles from ansible-galaxy CLI

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy-issues#186]
```
mordred@camelot:~/src/openstack-infra/shade$ ansible-galaxy -vvv delete openstack-infra ansible-role-puppet
No config file found; using defaults
Opened /home/mordred/.ansible_galaxy
https://galaxy.ansible.com/api/v1/removerole/?github_user=openstack-infra&github_repo=ansible-role-puppet
ERROR! Unexpected Exception: ('The read operation timed out',)
the full traceback was:

Traceback (most recent call last):
  File "/home/mordred/.local/bin/ansible-galaxy", line 92, in <module>
    exit_code = cli.run()
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 133, in run
    self.execute()
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/cli/__init__.py", line 103, in execute
    fn()
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 660, in execute_delete
    resp = self.api.delete_role(github_user, github_repo)
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 286, in delete_role
    data = self.__call_galaxy(url, headers=self.__auth_header(), method='DELETE')
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/galaxy/api.py", line 92, in __call_galaxy
    resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method)
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 839, in open_url
    r = urllib2.urlopen(*urlopen_args)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/mordred/.local/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 365, in https_open
    return self.do_open(CustomHTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
```

**Comment by chouseknecht** [comment]
I've seen this error intermittently. The timeout in Ansible's urls.py is set to 10 seconds. That seems like an eternity, but maybe there is actually a timeout occurring. May try setting the timeout higher in galaxy/api.py.

**Comment by chouseknecht** [comment]
Increased the timeout https://github.com/ansible/ansible/commit/77de83730d407f531d521ce3ee73fd803126ab56. This is part of Ansible 2.3 and available in the _devel_ branch.

Please re-open this issue, if this error continues.
