### ISSUE TITLE
Build fails due to version conflict with npm package "less"

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-issues#291]
NPM package `less` updated to version `3.0.0`, which causes a dependency check error while building galaxy containers:

```
/galaxy/node_modules/accord/lib/index.js:29
      throw new Error(name + " version " + version + " is not currently supported");
      ^

Error: less version 3.0.0-alpha.3 is not currently supported
    at Object.exports.load (/galaxy/node_modules/accord/lib/index.js:29:13)
    at Object.<anonymous> (/galaxy/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/galaxy/gulpfile.js:2:12)
```

**Comment by cutwater** [comment]
Fixed by ansible/galaxy#28
